### ISSUE TITLE
Step by Step Guide to Create an access token

### ISSUE THREAD

**Issue by arfrater** [tim-hellhake/spotify-adapter#1]
Hi
I've got so far but cannot figure out how to create the access token with the permission user-modify-playback-state. I have created an app on the spotify dashboard with client ID and secret but that's as far as I got. Is their any step by step guide. Possibly could be included in the Read.me file ? 
Thanks

**Comment by tim-hellhake** [comment]
I used the Spotify console: https://developer.spotify.com/console/post-next.
I'll add that to the docs.

**Comment by arfrater** [comment]
Done and got working ok Thanks
