### ISSUE TITLE
Album cover does not update when the track changes.

### ISSUE THREAD

**Issue by chasingmaxwell** [tim-hellhake/spotify-adapter#18]
When I first open the spotify thing interface and click through to the album cover it correctly gets the track which is currently playing. However, when the next track starts playing and I click through to the album cover, it continues to show the previous track. Clicking the "refresh" icon does not work either. The rest of the properties (artist, album, track) are all changing appropriately. Let me know what additional information I can provide. Thanks!

**Comment by tim-hellhake** [comment]
Thanks for the feedback!
I'll try to reproduce it.

**Comment by tim-hellhake** [comment]
I think i found the issue.
It should be fixed with the next update.

**Comment by chasingmaxwell** [comment]
Great! Thank you!

**Comment by tim-hellhake** [comment]
Can we close the issue or is there still a problem with the update?

**Comment by chasingmaxwell** [comment]
Confirmed today this is working. Thanks again!
