### ISSUE TITLE
INVALID_CLIENT: Invalid redirect URI

### ISSUE THREAD

**Issue by kratoskat** [tim-hellhake/spotify-adapter#21]
Hello,

So i've followed the below steps:

- Go to Spotify dev dashboard and created new app
-  Copied Client ID and Secret to Add on configuration and saved.
- Open URL to authenticate got populated and on nagivating to that URL i get the below error
INVALID_CLIENT: Invalid redirect URI 

any idea what the issue might me?

**Comment by tim-hellhake** [comment]
The callback URL needs to be added to your app.
Otherwise, Spotify will reject it.

**Comment by kratoskat** [comment]
I think i need a bit more guidance from you pls as i've never done this before. I apologise but couldn't see anything on the readme.

i have this url from you.
https://accounts.spotify.com/authorize?client_id={CLIENT_ID) &response_type=code&redirect_uri=https://ppacher.github.io/spotify-auth-callback&scope=user-read-playback-state%20user-modify-playback-state&state=

and i've done the below 

1) added redirect_uri to spotify and saved
![image](https://user-images.githubusercontent.com/46923294/89738543-70644300-da71-11ea-92d6-2292d950e9dc.png)

2) tried to click on auth url and still fails. I tried adding the redirect uri into the Redirect URI input but all it does is append the redirect uri again onto the auth url.
![image](https://user-images.githubusercontent.com/46923294/89738571-b3261b00-da71-11ea-878b-4bd4833f8d0d.png)

Am i missing anything?

**Comment by kratoskat** [comment]
Apologies! i missed that step of the instruction! thanks :)

**Comment by tim-hellhake** [comment]
No need to apologize.
I'm glad that it's working now :)
